### ISSUE TITLE
HTML export styles

### ISSUE THREAD

**Issue by hyphone** [ajilderda/joplin-macos-native-theme#39]
Hello and good day!

Thank you very much for this wonderful theme.
I wanted to start my own theme but since I found this there is no need anymore ;)

I have one issue though with HTML exports.

When I use the dark style and export an HTML file it's also styled dark and the H1 is not correctly colored.
Could you leave it to the default light style for exports or create a setting that exports won't be affected by the application style?

I don't have that issue with built in themes. When I use a built in dark theme the exports are still default white.

Best
marco

**Comment by ajilderda** [comment]
Hi @hyphone , I style the note preview via the `loadNoteCssFile`-method. I actually didn't expect that these styles  would be inserted into exported html-files also, but according to these Joplin plugins docs that is intentional:
https://github.com/joplin/plugin-templates/blob/add65341a3fda5220a7fa0a4ce0c4359800dea48/api/JoplinWindow.d.ts#L18

That means there is not much I can do, except a suggestion to switch the theme to light when exporting (or set it to auto and toggle the system's dark/light mode to prevent to having to restart Joplin every time ;)).
