### ISSUE TITLE
Uplift Theming to Include Entire Joplin App

### ISSUE THREAD

**Issue by ScriptInfra** [ajilderda/joplin-macos-native-theme#42]
Hello! Would it be possible to also theme parts of the Joplin app, such as the Options UI with this theme (Tools > Options)?

Additionally, I was also curious if the UI prompts could have the theme applied? E.g. check for updates, About Joplin.

![image](https://user-images.githubusercontent.com/63025323/143414328-fdf811a6-1a14-49a7-b79e-7e26951e4da3.png)

![image](https://user-images.githubusercontent.com/63025323/143414357-80c2c33a-6f1f-4fe1-b72e-96a7bbf1f75c.png)

**Comment by ajilderda** [comment]
Hi @ScriptInfra / Andrew, the UI prompts are native prompts by the OS and therefore can not be styled. The Joplin preferences can be styled, but I chose not to because 1. it would take a lot of time to do properly for little benefit, 2. is quite hacky because of the lack of classnames on a lot of elements and 3. is error-prone › if the theme would break something that prevent users from accessing the plugins settings they can not disable it... 😅

**Comment by ScriptInfra** [comment]
Hello @ajilderda - Thanks for the quick response! That definitely makes sense to me and I appreciate the insight.
